package com.example.login;

public class state_dist_array {
   public String state[]={"A & N ISLANDS","ANDHRA PRADESH","ARUNACHAL PRADESH","ASSAM","BIHAR","CHANDIGARH","CHHATTISGARH","PONDICHERRY","DAMAN & DIU","D & N HAVELI","GOA","GUJARAT","HARYANA","HIMACHAL PRADESH","JAMMU & KASHMIR","KARNATAKA","KERALA","LAKSHADWEEP","MADHYA PRADESH","MAHARASHTRA","MANIPUR","MEGHALAYA","MIZORAM","NAGALAND","ODISHA","PUNJAB","RAJASTHAN","SIKKIM","TAMIL NADU","TRIPURA","UTTAR PRADESH","UTTARAKHAND","WEST BENGAL"};
   public String[] ani={"ANDAMAN","NICOBAR"};
   public String anp[]={"ADILABAD","ANANTAPUR","CHITTOOR","CUDDAPAH","CYBERABAD","EAST GODAVARI","GUNTAKAL RLY.","GUNTUR","HYDERABAD CITY","KARIMNAGAR","KHAMMAM","KRISHNA","KURNOOL","MAHABOOBNAGAR","MEDAK","NALGONDA","NELLORE","NIZAMABAD","PRAKASHAM","RANGA REDDY","SECUNDERABAD RLY.","SRIKAKULAM","VIJAYAWADA RLY.","VISAKHA RURAL","VISAKHAPATNAM","VIZIANAGARAM","WARANGAL","WEST GODAVARI"};
   public  String arp[]={"CHANGLANG","DIBANG VALLEY","K/KUMEY","KAMENG EAST","KAMENG WEST","LOHIT","PAPUM PARE","SIANG EAST","SIANG UPPER","SIANG WEST","SUBANSIRI LOWER","SUBANSIRI UPPER","TAWANG","TIRAP","UPPER DIBANG VALLEY"};
   public  String assam[]={"BARPETA","BONGAIGAON","C.I.D.","CACHAR","CHIRANG","DARRANG","DHEMAJI","DHUBRI","DIBRUGARH","G.R.P.","GOALPARA","GOLAGHAT","GUWAHATI CITY","HAILAKANDI","JORHAT","KAMRUP","KARBI ANGLONG","KARIMGANJ","KOKRAJHAR","LAKHIMPUR","MORIGAON","N.C.HILLS","NAGAON","NALBARI","R.P.O.","SIBSAGAR","SONITPUR","TINSUKIA","UDALGURI"};
   public String bihar[]={"ARARIA","ARWAL","AURANGABAD","BAGAHA","BANKA","BEGUSARAI","BETTIAH","BHABHUA","BHAGALPUR","BHOJPUR","BUXAR","DARBHANGA","GAYA","GOPALGANJ","JAMALPUR RLY.","JAMUI","JEHANABAD","KATIHAR","KATIHAR RLY.","KHAGARIA","KISHANGANJ","LAKHISARAI","MADHEPURA","MADHUBANI","MOTIHARI","MUNGER","MUZAFFARPUR","MUZAFFARPUR RLY.","NALANDA","NAUGACHIA","NAWADAH","PATNA","PATNA RLY.","PURNEA","ROHTAS","SAHARSA","SAMASTIPUR","SARAN","SHEIKHPURA","SHEOHAR","SITAMARHI","SIWAN","SUPAUL","VAISHALI"};
   public String chandigarh[]={"CHANDIGARH"};
   public String chhattisgarh[]={"BALRAMPUR","BILASPUR","BIZAPUR","DANTEWARA","DHAMTARI","DURG","GRP RAIPUR","JAGDALPUR","JANJGIR","JASHPUR","KABIRDHAM","KANKER","KORBA","KORIYA","MAHASAMUND","NARAYANPUR","RAIGARH","RAIPUR","RAJNANDGAON","SARGUJA","SURAJPUR"};
   public String pondicherry[]={"PONDICHERRY"};
   public  String dad[]={"DAMAN","DIU"};
   public String dnh[]={"D & N HAVELI"};
   public  String goa[]={"NORTH GOA","SOUTH GOA"};
   public String gujrat[]={"AHMEDABAD COMMR.","AHMEDABAD RURAL","AHWA-DANG","AMRELI","ANAND","BHARUCH","BHAVNAGAR","DAHOD","GANDHINAGAR","HIMATNAGAR","JAMNAGAR","JUNAGADH","KHEDA NORTH","KUTCH","MEHSANA","NARMADA","NAVSARI","PALANPUR","PANCHMAHAL","PATAN","PORBANDAR","RAJKOT COMMR.","RAJKOT RURAL","SURAT COMMR.","SURAT RURAL","SURENDRANAGAR","VADODARA COMMR.","VADODARA RURAL","VALSAD","W.RLY"};
   public  String haryana[]={"AMBALA","BHIWANI","FARIDABAD","FATEHABAD","GRP","GURGAON","HISSAR","JHAJJAR","JIND","KAITHAL","KARNAL","KURUKSHETRA","MAHENDRAGARH","MEWAT","PALWAL","PANCHKULA","PANIPAT","REWARI","ROHTAK","SIRSA","SONIPAT","YAMUNANAGAR"};
   public String hp[]={"BILASPUR","CHAMBA","G.R.P.","HAMIRPUR","KANGRA","KINNAUR","KULLU","LAHAUL-SPITI","MANDI","SHIMLA","SIRMAUR","SOLAN","UNA"};
   public  String jk[]={"ANANTNAG","AWANTIPORA","BARAMULLA","BUDGAM","CRIME JAMMU","CRIME SRINAGAR","DODA","GANDERBAL","HANDWARA","JAMMU","KARGIL","KATHUA","KULGAM","KUPWARA","LEH","POONCH","PULWAMA","RAILWAYS","RAJOURI","RAMBAN","REASI","SRINAGAR","UDHAMPUR"};
   public  String kar[]={"BAGALKOT","BANGALORE COMMR.","BANGALORE RURAL","BELGAUM","BELLARY","BIDAR","BIJAPUR","CHAMARAJNAGAR","CHICKMAGALUR","CHITRADURGA","DAKSHIN KANNADA","DAVANAGERE","DHARWAD COMMR.","DHARWAD RURAL","GADAG","GULBARGA","HASSAN","HAVERI","K.G.F.","KODAGU","KOLAR","KOPPAL","MANDYA","MYSORE COMMR.","MYSORE RURAL","RAICHUR","RAILWAYS","SHIMOGA","TUMKUR","UDUPI","UTTAR KANNADA"};
    public  String ld[]={"LAKSHADWEEP"};
    public  String mp[]={"ANUPPUR","ASHOK NAGAR","BALAGHAT","BARWANI","BETUL","BHIND","BHOPAL","BHOPAL RLY.","BURHANPUR","CHHATARPUR","CHHINDWARA","DAMOH","DATIYA","DEWAS","DHAR","DINDORI","GUNA","GWALIOR","HARDA","HOSHANGABAD","INDORE","INDORE RLY.","JABALPUR","JABALPUR RLY.","JHABUA","KATNI","KHANDWA","KHARGON","MANDLA","MANDSAUR","MORENA","NARSINGHPUR","NEEMUCH","PANNA","RAISEN","RAJGARH","RATLAM","REWA","SAGAR","SATNA","SEONI","SHAHDOL","SHAJAPUR","SHEOPUR","SHIVPURI","SIDHI","SIHORE","TIKAMGARH","UJJAIN","UMARIYA","VIDISHA"};
    public  String ker[]={"ALAPUZHA","ERNAKULAM COMMR.","ERNAKULAM RURAL","IDUKKI","KANNUR","KASARGOD","KOLLAM","KOTTAYAM","KOZHIKODE COMMR.","KOZHIKODE RURAL","MALAPPURAM","PALAKKAD","PATHANAMTHITTA","RAILWAYS","THRISSUR","TRIVANDRUM COMMR.","TRIVANDRUM RURAL","WAYANADU"};
    public  String mh[]={"AHMEDNAGAR","AKOLA","AMRAVATI COMMR.","AMRAVATI RURAL","AURANGABAD COMMR.","AURANGABAD RURAL","BEED","BHANDARA","BULDHANA","CHANDRAPUR","DHULE","GADCHIROLI","GONDIA","HINGOLI","JALGAON","JALNA","KOLHAPUR","LATUR","MUMBAI","MUMBAI RLY.","NAGPUR COMMR.","NAGPUR RLY.","NAGPUR RURAL","NANDED","NANDURBAR","NASIK COMMR.","NASIK RURAL","NAVI MUMBAI","OSMANABAD","PARBHANI","PUNE COMMR.","PUNE RLY.","PUNE RURAL","RAIGAD","RATNAGIRI","SANGLI","SATARA","SINDHUDURG","SOLAPUR COMMR.","SOLAPUR RURAL","THANE COMMR.","THANE RURAL","WARDHA","WASHIM","YAVATMAL"};
    public  String mn[]={"BISHNUPUR","CHANDEL","CHURACHANDPUR","IMPHAL EAST","IMPHAL WEST","SENAPATI","TAMENGLONG","THOUBAL","UKHRUL"};
    public  String  mg[]={"GARO HILLS EAST","GARO HILLS SOUTH","GARO HILLS WEST","JAINTIA HILLS","KHASI HILLS EAST","KHASI HILLS WEST","RI-BHOI"};
    public  String mz[]={"AIZAWL","CHAMPHAI","KOLASIB","LAWNGTLAI","LUNGLEI","MAMIT","SAIHA","SERCHHIP"};
    public  String ng[]={"DIMAPUR","KIPHIRE","KOHIMA","MOKOKCHUNG","MON","PEREN","PHEK","TUENSANG","WOKHA","ZUNHEBOTO"};
    public String od[]={"ANGUL","BALASORE","BARAGARH","BERHAMPUR","BHADRAK","BOLANGIR","BOUDH","CUTTACK","DEOGARH","DHENKANAL","GAJAPATI","GANJAM","JAGATSINGHPUR","JAJPUR","JHARSUGUDA","KALAHANDI","KANDHAMAL","KENDRAPARA","KEONJHAR","KHURDA","KORAPUT","MALKANGIR","MAYURBHANJ","NAYAGARH","NOWRANGPUR","NUAPADA","PURI","RAYAGADA","ROURKELA","SAMBALPUR","SONEPUR","SRP(CUTTACK)","SRP(ROURKELA)","SUNDARGARH"};
    public String pun[]={"AMRITSAR","BARNALA","BATALA","BHATINDA","FARIDKOT","FATEHGARH SAHIB","FEROZPUR","G.R.P","GURDASPUR","HOSHIARPUR","JALANDHAR","KAPURTHALA","KHANNA","LUDHIANA","MANSA","MOGA","MUKTSAR","PATIALA","ROPAR","SANGRUR","SAS NGR","TARN TARAN"};
    public String raj[]={"AJMER","ALWAR","BANSWARA","BARAN","BARMER","BHARATPUR","BHILWARA","BIKANER","BUNDI","CHITTORGARH","CHURU","DAUSA","DHOLPUR","DUNGARPUR","G.R.P.","GANGANAGAR","HANUMANGARH","JAIPUR EAST","JAIPUR NORTH","JAIPUR RURAL","JAIPUR SOUTH","JAISALMER","JALORE","JHALAWAR","JHUNJHUNU","JODHPUR CITY","JODHPUR RURAL","KARAULI","KOTA CITY","KOTA RURAL","NAGAUR","PALI","RAJSAMAND","SAWAI MADHOPUR","SIKAR","SIROHI","TONK","UDAIPUR"};
    public String sk[]={"EAST","NORTH","SOUTH","WEST"};
    public String tn[]={"CHENGAI","CHENNAI","CHENNAI RLY.","COIMBATORE RURAL","COIMBATORE URBAN","CUDDALORE","DHARMAPURI","DINDIGUL","ERODE","KANCHIPURAM","KANYAKUMARI","KARUR","KRISHNAGIRI","MADURAI RURAL","MADURAI URBAN","NAGAPATTINAM","NAMAKKAL","NILGIRIS","PERAMBALUR","PUDUKOTTAI","RAMNATHAPURAM","SALEM RURAL","SALEM URBAN","SIVAGANGAI","THANJAVUR","THENI","THIRUNELVELI RURAL","THIRUNELVELI URBAN","THIRUVALLUR","THIRUVANNAMALAI","THIRUVARUR","THOOTHUGUDI","TRICHY RLY.","TRICHY RURAL","TRICHY URBAN","VELLORE","VILLUPURAM","VIRUDHUNAGAR"};
    public String tr[]={"DHALAI","NORTH","SOUTH","WEST"};
    public String up[]={"AGRA","ALIGARH","ALLAHABAD","AMBEDKAR NAGAR","AURAIYA","AZAMGARH","BADAUN","BAGHPAT","BAHRAICH","BALLIA","BALRAMPUR","BANDA","BARABANKI","BAREILLY","BASTI","BIJNOR","BULANDSHAHAR","CHANDOLI","CHITRAKOOT DHAM","DEORIA","ETAH","ETAWAH","FAIZABAD","FATEHGARH","FATEHPUR","FIROZABAD","G.R.P.","GAUTAMBUDH NAGAR","GHAZIABAD","GHAZIPUR","GONDA","GORAKHPUR","HAMIRPUR","HARDOI","HATHRAS","J.P.NAGAR","JALAUN","JAUNPUR","JHANSI","KANNAUJ","KANPUR DEHAT","KANPUR NAGAR","KAUSHAMBI","KHIRI","KUSHI NAGAR","LALITPUR","LUCKNOW","MAHARAJGANJ","MAHOBA","MAINPURI","MATHURA","MAU","MEERUT","MIRZAPUR","MORADABAD","MUZAFFARNAGAR","PILIBHIT","PRATAPGARH","RAIBAREILLY","RAMPUR","SAHARANPUR","SANT KABIRNAGAR","SHAHJAHANPUR","SHRAWASTI","SIDHARTHNAGAR","SITAPUR","SONBHADRA","ST.RAVIDASNAGAR","SULTANPUR","UNNAO","VARANASI"};
    public String uk[]={"ALMORA","BAGESHWAR","CHAMOLI","CHAMPAWAT","DEHRADUN","HARIDWAR","NAINITAL","PAURI GARHWAL","PITHORAGARH","RUDRA PRAYAG","TEHRI GARHWAL","UDHAMSINGH NAGAR","UTTARKASHI"};
    public String wb[]={"24 PARGANAS NORTH","24 PARGANAS SOUTH","ASANSOL","BANKURA","BIRBHUM","BURDWAN","COOCHBEHAR","DAKSHIN DINAJPUR","DARJEELING","HOOGHLY","HOWRAH","HOWRAH CITY","HOWRAH G.R.P.","JALPAIGURI","KHARAGPUR G.R.P.","KOLKATA","MALDA","MURSHIDABAD","NADIA","PASCHIM MIDNAPUR","PURAB MIDNAPUR","PURULIA","SEALDAH G.R.P.","SILIGURI G.R.P.","UTTAR DINAJPUR"};





   public String[] select(String s){
       switch (s){
           case "A & N ISLANDS":
               return ani;
           case "ANDHRA PRADESH":
               return anp;
           case "ARUNACHAL PRADESH":
               return arp;
           case "ASSAM":
               return assam;
           case "BIHAR":
               return bihar;
           case "CHANDIGARH":
               return chandigarh;
           case "CHHATTISGARH":
               return chhattisgarh;
           case "PONDICHERRY":
               return pondicherry;
           case "DAMAN & DIU":
               return dad;
           case "D & N HAVELI":
               return dnh;
           case "GOA":
               return goa;
           case "GUJARAT":
               return gujrat;
           case "HARYANA":
               return haryana;
           case "HIMACHAL PRADESH":
               return hp;
           case "JAMMU & KASHMIR":
               return jk;
           case "KARNATAKA":
               return kar;
           case "KERALA":
               return ker;
           case "LAKSHADWEEP":
               return ld;
           case "MADHYA PRADESH":
               return mp;
           case "MAHARASHTRA":
               return mh;
           case "MANIPUR":
               return mn;
           case "MEGHALAYA":
               return mg;
           case "MIZORAM":
               return mz;
           case "NAGALAND":
               return ng;
           case "ODISHA":
               return od;
           case "PUNJAB":
               return pun;
           case "RAJASTHAN":
               return raj;
           case "SIKKIM":
               return sk;
           case "TAMIL NADU":
               return tn;
           case "TRIPURA":
               return tr;
           case "UTTAR PRADESH":
               return up;
           case "UTTARAKHAND":
               return uk;
           case "WEST BENGAL":
               return wb;


       }
       return new String[0];
   }

}
